spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.weijx.springcloud.pojo
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: newpwd
logging:
    level:
      com.weijx.springcloud.controller: debug
      com.weijx.springcloud.dao: trace
      org:
        springframework: debug
        mybatis: debug
        apache:
          ibatis: debug
#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001

info:
  app.name: weijx-springcloud
  company.name: zdww
---
server:
  port: 8001
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.weijx.springcloud.pojo
spring:
  profiles: test
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: newpwd
logging:
    level:
      com.weijx.springcloud.controller: debug
      com.weijx.springcloud.dao: trace
      org:
        springframework: debug
        mybatis: debug
        apache:
          ibatis: debug
#Eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001

info:
  app.name: weijx-springcloud
  company.name: zdww